### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by konpa** [190n/open-doc#1]
Will it be possible to add a config file where the default browser could be changed?

**Comment by 190n** [comment]
Not quite sure if this is possible. I'll add a config file and see if the package can still read it once it's been installed. I'm guessing it can, though.

**Comment by 190n** [comment]
Sorry, I got totally sidetracked. I can't figure out if/how this is possible. I'm not very experienced with Atom packages. The browser setting is stored in the filesystem, so if you're worried about portability, that shouldn't be an issue.
